### ISSUE TITLE
Add `template` in settings

### ISSUE THREAD

**Issue by idkjs** [reason-native-web/morph_template#1]
<img width="438" alt="Screenshot 2019-10-03 at 9 16 02 AM" src="https://user-images.githubusercontent.com/2370391/66129739-81753580-e5be-11e9-9a67-9a04c15433ee.png"> ?

**Comment by ulrikstrid** [comment]
You want me to make this repo a template?

**Comment by idkjs** [comment]
If that was the point, you should. If its just to use to pass to esy --template then idk. Making a suggestion, sir.

**Comment by ulrikstrid** [comment]
Sure, I will do that 👍 this repo is just what gets generated from the pesy template.

**Comment by ulrikstrid** [comment]
Done
